In [1]:
for i in range(1,5):
    for j in range(5,10):
        for nij in range(11,15):
            print(i,j,nij)

1 5 11
1 5 12
1 5 13
1 5 14
1 6 11
1 6 12
1 6 13
1 6 14
1 7 11
1 7 12
1 7 13
1 7 14
1 8 11
1 8 12
1 8 13
1 8 14
1 9 11
1 9 12
1 9 13
1 9 14
2 5 11
2 5 12
2 5 13
2 5 14
2 6 11
2 6 12
2 6 13
2 6 14
2 7 11
2 7 12
2 7 13
2 7 14
2 8 11
2 8 12
2 8 13
2 8 14
2 9 11
2 9 12
2 9 13
2 9 14
3 5 11
3 5 12
3 5 13
3 5 14
3 6 11
3 6 12
3 6 13
3 6 14
3 7 11
3 7 12
3 7 13
3 7 14
3 8 11
3 8 12
3 8 13
3 8 14
3 9 11
3 9 12
3 9 13
3 9 14
4 5 11
4 5 12
4 5 13
4 5 14
4 6 11
4 6 12
4 6 13
4 6 14
4 7 11
4 7 12
4 7 13
4 7 14
4 8 11
4 8 12
4 8 13
4 8 14
4 9 11
4 9 12
4 9 13
4 9 14


In [5]:
import numpy as np

In [8]:
np.concatenate([np.concatenate([[[i,j,nij] for nij in range(11,15)] for j in range(5,10)]) for i in range(1,5)])

array([[ 1,  5, 11],
       [ 1,  5, 12],
       [ 1,  5, 13],
       [ 1,  5, 14],
       [ 1,  6, 11],
       [ 1,  6, 12],
       [ 1,  6, 13],
       [ 1,  6, 14],
       [ 1,  7, 11],
       [ 1,  7, 12],
       [ 1,  7, 13],
       [ 1,  7, 14],
       [ 1,  8, 11],
       [ 1,  8, 12],
       [ 1,  8, 13],
       [ 1,  8, 14],
       [ 1,  9, 11],
       [ 1,  9, 12],
       [ 1,  9, 13],
       [ 1,  9, 14],
       [ 2,  5, 11],
       [ 2,  5, 12],
       [ 2,  5, 13],
       [ 2,  5, 14],
       [ 2,  6, 11],
       [ 2,  6, 12],
       [ 2,  6, 13],
       [ 2,  6, 14],
       [ 2,  7, 11],
       [ 2,  7, 12],
       [ 2,  7, 13],
       [ 2,  7, 14],
       [ 2,  8, 11],
       [ 2,  8, 12],
       [ 2,  8, 13],
       [ 2,  8, 14],
       [ 2,  9, 11],
       [ 2,  9, 12],
       [ 2,  9, 13],
       [ 2,  9, 14],
       [ 3,  5, 11],
       [ 3,  5, 12],
       [ 3,  5, 13],
       [ 3,  5, 14],
       [ 3,  6, 11],
       [ 3,  6, 12],
       [ 3,  6, 13],
       [ 3,  

In [9]:
np.array([1,2,34])

array([ 1,  2, 34])

In [13]:
type(np.array([1,2,34])) == np.ndarray

True

In [1]:
from rpy2.robjects import r

In [3]:
# https://github.com/clajusch/ClEvaR/blob/master/R/Calculations.R
test = r("""
EMI <- function(subject, query) {
  mi <- MI(subject, query)
  s1 <- tabulate(subject)
  s2 <- tabulate(query)
  N <- length(subject)
  l1 <- length(s1)
  l2 <- length(s2)
  s_emi <- 0
  for(i in 1:l1){
    for (j in 1:l2){
      min_nij <- max(1,s1[i]+s2[j]-N)
      max_nij <- min(s1[i],s2[j])
      n.ij <- seq(min_nij, max_nij)   #sequence of consecutive numbers
      t1<- (n.ij / N) * log((n.ij * N) / (s1[i]*s2[j]))
      t2 <- exp(lfactorial(s1[i]) +
                  lfactorial(s2[j]) +
                  lfactorial(N - s1[i]) +
                  lfactorial(N - s2[j]) -
                  lfactorial(N) -
                  lfactorial(n.ij) -
                  lfactorial(s1[i] - n.ij) -
                  lfactorial(s2[j] - n.ij) -
                  lfactorial(N - s1[i] - s2[j] + n.ij))
      emi <- sum(t1*t2)
      s_emi <- s_emi + emi
    }
  }
  return(s_emi)
}
""")

In [4]:
test.

R object with classes: ('function',) mapped to:

In [6]:
import numpy as np

In [17]:
a = np.repeat(range(4), 3)
a

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [13]:
b = np.tile(range(3), 3)
b

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [16]:
np.vstack([a,b]).T

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [20]:
[[i, j] for i in range(4) for j in range(5)]

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [2, 4],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3],
 [3, 4]]

In [21]:
np.outer([1,2,3], [4,5,6])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])